config/routes.rb
Rails.application.routes.draw do

  root to: 'products#index'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  get '/cart' => 'carts#user_cart'

  resources :users, except: [:index]
  resources :products, only: [:index, :show]
  resources :carts, only: [:create, :destroy]
  resources :line_items, only: [:create, :update, :destroy]
  resources :orders, only: [:create, :show]

  get '/order/confirm_order' => 'orders#confirm_order', as: 'confirm_order'
  post '/order/payment' => 'orders#payment', as: 'payment'
  get '/order/complete_order' => 'orders#complete_order', as: 'complete_order'
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :line_items, dependent: :destroy
  belongs_to :user

  # 'Moves' a customer's line items from their cart to their order following successful payment
  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      # Set the item's cart_id to nil so that line_items are no longer associated with the (so to be destroyed) cart
      item.cart_id = nil
      # Add the current line item to @order.line_items, so that the order_id
      # is automatically filled in by Rails
      self.line_items << item
    end
  end

  # Update stock levels aftet the completion of a successful order
  def update_inventory
    self.line_items.each do |item|
      update_qty = item.product_size.quantity - item.quantity
      item.product_size.update quantity: update_qty
    end
  end

  # Shortcut to the customer's details that are stored in the stripe_charge_repsonse column of the orders table
  def customer_details
    self.stripe_charge_response["source"]
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :fetch_cart_and_check_inventory, except: [:show]

  # User routed here from click on 'Checkout' button on My Basket page (carts#user_cart)
  def create
    # Invokes action in cart.rb that checks whether the cart is empty
    if @cart.is_cart_empty?
      # If the cart is empty, set flash error and redirect to My Basket page
      flash[:item_error] = "Your cart is empty."
      redirect_to cart_path
      return
    end

    # Create order and redirect to orders#confirm_order
    @order = Order.create user_id: @current_user.id
    redirect_to confirm_order_path
  end

  # User routed here after creating new order
  def confirm_order
  end

  # User routed here after clicking on Stripe's 'Pay with Card'
  # button on orders#confirm_order and then completing the payment
  # form within the Stripe Checkout window
  # Note: Checkout sends the payment details directly to Stripe from
  # the customer's browser, assuming the details pass basic validation
  def payment
    # Get the current user's last order (i.e. the current order)
    @order = @current_user.orders.last

    # Token automatically created by Checkout and sent through params
    token = params[:stripeToken]

    # Invoke action in cart.rb that calculates the total price of all items in the cart
    total_amount = (@cart.get_total_price * 100).to_i

    Stripe.api_key = Rails.application.secrets.stripe_api_secret

    # Make an API request to create a one-time charge containing the token,
    # currency, total amount (as an integer not a float) and description
    charge = Stripe::Charge.create({
    amount: total_amount,
    currency: 'aud',
    description: 'Purchase from Eight by Eight',
    source: token,
    })

    # Update the current order with the Stripe charge response data
    @order.update stripe_token: token, stripe_charge_response: charge

    # Checks whether the payment was successful
    unless @order.stripe_charge_response["outcome"]["network_status"] == "approved_by_network"
      # If the payment was unsuccessful, set a flash error and redirect to orders#confirm_order
      flash[:order_error] = "Transaction unsuccessful. Please contact your card issuer for more details."
      redirect_to confirm_order_path
      return
    end

    # Redirect to orders#complete_order
    redirect_to complete_order_path
  end

  # User routed here after successful payment
  def complete_order
    # Get the current user's last order (i.e. the current order)
    @order = @current_user.orders.last

    # Invoke an action in order.rb that 'moves' items from a user's cart to the current order
    @order.add_line_items_from_cart @cart

    # Invoke action in order.rb that updates stock levels
    @order.update_inventory

    # Destroy the user's cart
    @cart.destroy

    # Set a flash notification that the order was successful
    flash[:notification] = "Order successful!!!"

    # Redirect to orders#show
    redirect_to order_path(@order)
  end

  def show
    @order = Order.find params[:id]
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/confirm_order.html.erb
<h2>Confirm Order</h2>

<% if flash[:order_error].present? %>
  <strong><%= flash[:order_error] %></strong>
<% end %>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Size</th>
      <th>Price</th>
      <th>Qty</th>
      <th>Subtotal</th>
    </tr>
  </thead>

  <tbody>
    <% @cart.line_items.each do |item| %>
      <tr>
        <td><%= link_to item.product.name, product_path(item.product) %></td>
        <td><%= item.product_size.size %></td>
        <td><%= number_to_currency(item.product.price) %></td>
        <td><%= item.quantity %></td>
        <td><%= number_to_currency(item.get_subtotal) %></td>
      </tr>
    <% end %>
  </tbody>

  <tfoot>
    <tr>
      <td colspan="4" class="total-price">Total Price:</td>
      <td><%= number_to_currency(@cart.get_total_price) %></td>
    </tr>
  </tfoot>
</table>

<%= form_tag payment_path do %>
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="pk_test_ABPwpcBRExR2PGKF6RCxqW8h"
    data-amount="<%= (@cart.get_total_price * 100).to_i %>"
    data-name="8 x 8"
    data-description="Order #<%= @current_user.orders.last.id %>"
    data-image="https://i.imgur.com/K9GQZAe.png"
    data-locale="auto"
    data-currency="aud"
    data-shipping-address=true>
  </script>
<% end %>

<%= link_to 'Back to Cart', cart_path, class: 'back-to-cart' %>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/index.html.erb
<h1>Orders#index</h1>
<p>Find me in app/views/orders/index.html.erb</p>

app/views/orders/show.html.erb
<h2>Order #<%= @order.id %></h2>

<% if flash[:notification].present? %>
  <p class="notification"><span><%= flash[:notification] %></span></p>
<% end %>

<h3>Order Summary</h3>
<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Size</th>
      <th>Qty</th>
      <th>Price</th>
      <th>Subtotal</th>
    </tr>
  </thead>

  <tbody>
    <% @order.line_items.each do |item| %>
      <tr>
        <td><%= link_to item.product.name, product_path(item.product) %></td>
        <td><%= item.product_size.size %></td>
        <td><%= item.quantity %></td>
        <td><%= number_to_currency(item.product.price) %></td>
        <td><%= number_to_currency(item.get_subtotal) %></td>
      </tr>
    <% end %>
  </tbody>

  <tfoot>
    <tr>
      <td colspan="4" class="total-price">Total:</td>
      <td><%= number_to_currency(@order.stripe_charge_response["amount"] / 100) %></td>
    </tr>
  </tfoot>
</table>

<div class="grid-container">
  <div class="grid-item">
    <h3>Shipping Details</h3>
    <p><%= @order.customer_details["name"] %></p>
    <p><%= @order.customer_details["address_line1"] %></p>
    <p><%= @order.customer_details["address_city"] %>,
       <%= @order.customer_details["address_state"] %>,
       <%= @order.customer_details["address_zip"] %></p>
    <p><%= @order.customer_details["address_country"] %></p>
  </div>

  <div class="grid-item">
    <h3>Payment Date</h3>
    <p><%= @order.updated_at.strftime("%b %d, %Y") %></p>

    <h3 class="payment-method">Payment Method</h3>
    <p><%= @order.customer_details["brand"] %></p>
  </div>
</div>