config/routes.rb
Rails.application.routes.draw do

  root to: 'products#index'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  get '/cart' => 'carts#user_cart'

  resources :users, except: [:index]
  resources :products, only: [:index, :show]
  resources :carts, only: [:create, :destroy]
  resources :line_items, only: [:create, :update, :destroy]
  resources :orders, only: [:create, :show]

  get '/order/confirm_order' => 'orders#confirm_order', as: 'confirm_order'
  post '/order/payment' => 'orders#payment', as: 'payment'
  get '/order/complete_order' => 'orders#complete_order', as: 'complete_order'
end

app/models/cart.rb
class Cart < ApplicationRecord

  has_many :line_items
  belongs_to :user
  # Ensures users only have one cart
  validates :user, uniqueness: true

  # Gets the total price of all items in the cart
  def get_total_price
    self.line_items.sum { |item| item.get_subtotal }
  end

  # Checks whether the cart is empty or not
  def is_cart_empty?
    total_price = self.get_total_price

    if total_price > 0
      return false
    else
      return true
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_action :check_if_logged_in, :fetch_cart_and_check_inventory

  # My Basket
  def user_cart
    render :show
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/create.html.erb
<h1>Carts#create</h1>
<p>Find me in app/views/carts/create.html.erb</p>

app/views/carts/show.html.erb
<h2>Shopping Basket</h2>

<% if flash[:item_error].present? %>
  <p class="error">
    <span><%= flash[:item_error] %></span>
  </p>
<% end %>

<% if @cart.line_items.length > 0 %>
  <table>
    <thead>
      <tr>
        <th>Item</th>
        <th>Size</th>
        <th>Price</th>
        <th>Subtotal</th>
        <th>Qty</th>
      </tr>
    </thead>

    <tbody>
      <% @cart.line_items.order(created_at: :desc).each do |item| %>
        <tr>
          <td><%= link_to item.product.name, product_path(item.product) %></td>
          <td><%= item.product_size.size %></td>
          <td><%= number_to_currency(item.product.price) %></td>
          <td><%= number_to_currency(item.get_subtotal) %></td>

          <td>
            <%= form_tag line_item_path(item.id), method: 'patch' do %>
              <%= text_field_tag :quantity, item.quantity, class: 'quantity' %>
              <%= submit_tag 'Update' %>
            <% end %>
          </td>
          <td><%= button_to 'Remove', line_item_path(item.id), method: 'delete' %></td>
        </tr>
      <% end %>
    </tbody>

    <tfoot>
      <tr>
        <td colspan="3" class="total-price">Total Price:</td>
        <td><%= number_to_currency(@cart.get_total_price) %></td>
      </tr>
    </tfoot>
  </table>

  <%= button_to 'Checkout', orders_path %>


<% else %>
  <p>Your shopping basket is currently empty.</p>
<% end %>