config/routes.rb
Rails.application.routes.draw do

  root to: 'products#index'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  get '/cart' => 'carts#user_cart'

  resources :users, except: [:index]
  resources :products, only: [:index, :show]
  resources :carts, only: [:create, :destroy]
  resources :line_items, only: [:create, :update, :destroy]
  resources :orders, only: [:create, :show]

  get '/order/confirm_order' => 'orders#confirm_order', as: 'confirm_order'
  post '/order/payment' => 'orders#payment', as: 'payment'
  get '/order/complete_order' => 'orders#complete_order', as: 'complete_order'
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :images
  has_many :product_sizes
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  # Home page
  def index
    @products = Product.all
  end

  def show
    @product = Product.find params[:id]
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<h2><%= Date.today.strftime("%B %Y") %></h2>

<div class="grid-container">

  <% @products.each do |product| %>
    <div class="grid-item">
      <a href="<%= product_path(product) %>">
        <%= image_tag product.images.first.image %>
      </a>
    </div>
  <% end %>

  <div class="grid-item last-cell">
    <p>EIGHT BY EIGHT</p>
  </div>

</div>

app/views/products/show.html.erb
<h2><%= @product.brand %></h2>

<div class="grid-container">
  <div class="grid-item">
    <% @product.images.each do |image| %>
      <%= image_tag image.image, alt: @product.name %>
    <% end %>
  </div><!-- grid-item -->

  <div class="grid-item">
    <h3><%= @product.name %></h3>

    <p class="description"><%= @product.description %></p>

    <p class="price"><%= number_to_currency(@product.price) %> AUD</p>


    <%= form_tag line_items_path  do %>
      <%= select_tag :product_size_id,
        options_for_select(
          @product.product_sizes.order(:size).pluck :size, :id
        ) %>

      <%= submit_tag 'Add to Cart' %>
    <% end %>
  </div><!-- grid-item -->
</div><!-- grid-container -->